apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  # labels of deployment resources
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: nginx
        image: gopi310/app1:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service
metadata:
  name: app1
spec:
  selector: # labels are used as selectors
    app: app1
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80
